### ISSUE TITLE
Ubuntu PPA: builds for 20.04 Focal Fossa

### ISSUE THREAD

**Issue by timvisee** [mumble-voip/mumble-ubuntu-ppa#11]
The official Ubuntu PPA for Mumble currently doesn't provide builds for Ubuntu 20.04 (Focal Fossa), the latest LTS release:
https://launchpad.net/~mumble/+archive/ubuntu/release

Are there any plans for this to be added?

**Comment by Kissaki** [comment]
@davidebeatrici PR #9 added this? So what’s the status of that? Was that your intention? Or what was that PR for if not for adding focal??

**Comment by Kissaki** [comment]
Looks like it was not published.

@davidebeatrici I would appreciate answers. And also if in the future a PR intent were clear, and if non-functioning stuff is merged into master that that is very clear.

**Comment by davidebeatrici** [comment]
![](https://user-images.githubusercontent.com/5897523/87842514-41f9aa80-c8ad-11ea-9c85-68694daa28ec.png)

I added `focal` to the list and triggered a release for it.

**Comment by davidebeatrici** [comment]
@blandin reports the package (https://github.com/mumble-voip/mumble/issues/4373#issuecomment-660479827) to be working correctly.
