### ISSUE TITLE
Merge ppa patches back into master

### ISSUE THREAD

**Issue by hacst** [mumble-voip/mumble-ubuntu-ppa#2]
Unless they contain some extreme Ubuntuism I see no reason why we should have additional patches applied on top of our upstream source package.

**Comment by mkrautz** [comment]
The lsb description patch should be fine to merge.

The logrotate is Debian specific, because it uses the username 'mumble-server'...

**Comment by hacst** [comment]
Isn't the whole repo debian specific? ;)
