### ISSUE TITLE
Can't install recent packages on Ubuntu 12.04 LTS

### ISSUE THREAD

**Issue by bsiegel** [mumble-voip/mumble-ubuntu-ppa#4]
Since 544225f, packages can't be installed on Ubuntu 12.04 due to missing dependency libqt5sql5-sqlite. Seems like the backport script should have been updated to swap this dependency out for libqt4-sql-sqlite but wasn't.

**Comment by hacst** [comment]
Should be fixed with the next snapshot/release once that arrives. Please report back if it isn't.
