### ISSUE TITLE
snapshot and release PPA broken at least for precise

### ISSUE THREAD

**Issue by momo-aux** [mumble-voip/mumble-ubuntu-ppa#6]
add-apt-repository ppa:mumble/release                                                                           :(
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 128, in <module>
    ppa_info = get_ppa_info_from_lp(user, ppa_name)
  File "/usr/lib/python2.7/dist-packages/softwareproperties/ppa.py", line 84, in get_ppa_info_from_lp
    curl.perform()
pycurl.error: (35, 'gnutls_handshake() failed: A TLS warning alert has been received.')

If I add by hand:
deb http://ppa.launchpad.net/mumble/release/ubuntu precise main

I get (on apt-get update)
W: Failed to fetch http://ppa.launchpad.net/mumble/release/ubuntu/dists/precise/main/binary-amd64/Packages  404  Not Found [IP: 2a01:488:66:1000:5c33:8591:0:1 80]

W: Failed to fetch http://ppa.launchpad.net/mumble/release/ubuntu/dists/precise/main/binary-i386/Packages  404  Not Found [IP: 2a01:488:66:1000:5c33:8591:0:1 80]

And yes, there is no Package file in the folder, just .bz2 and .gz 
Also tried to add the key via:
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 0x85DECED27F05CF9E

**Comment by Kissaki** [comment]
Sorry for the late reply. I fixed our PPA builds for current supported versions.

Precise support ended last year. We run into a type conversion issue when compiling on precise, possibly to a compiler or stdlib bug. We have more important things to time into, so I'm calling support on precise off as Ubuntu precise is end of life anyway. Please refer to a more recent distro package (or compile it yourself for precise).
